name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Lint with Clippy
      run: cargo clippy --all-targets --all-features -- -D warnings
    - name: Check
      run: cargo check --verbose
    - name: Run tests
      run: cargo test --verbose
